### ISSUE TITLE
Stuck on "Loading..."

### ISSUE THREAD

**Issue by AlxndrJhn** [lucashc/FastReader#3]
The console logs
Click on `start` with 400 wpm leads to

```bash
Element injected fastreader.js:104:13
Start word viewer fastreader.js:105:13
Do show! fastreader.js:46:11
In Interval 192 fastreader.js:55:15
```

I am using Firefox Browser
70.0.1 (64-bit)

I use uBlock Origin as well

**Comment by lucashc** [comment]
Hi AlxndrJhn,
Excuse me for the late reply, I have been busy and did not actively maintain this project for a while. Concerning you issue: As `In Interval 192 fastreader.js:55:15` is printed, it seems like at least 192 iterations of the interval have executed, but somehow failed to show the content on screen. I have tested the extension on Firefox 70.0.1 (64 bit) with uBlock origin as well, but did not have any problems. Do you use any other extensions?

**Comment by AlxndrJhn** [comment]
Yes I do use other extensions as well, as I use a different extension, I will close this issue
